[package]
name = "jokers"
version = "0.1.0"
edition = "2024"
authors = ["ysoseriouz"]
license = "MIT"
description = "API wrapper for https://v2.jokeapi.dev/"
readme = "README.md"
keywords = ["api", "joke"]
